services:
  _defaults:
    autowire: true
    autoconfigure: true

  Alexain\SimpleSpreadsheetReader\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection'
      - '../../SimpleSpreadsheetReaderBundle.php'
